trigger: 'none' # will disable CI builds entirely
# - master
pr: none
# - master
# - releases/*

jobs:
- job: WebApp
  displayName: 'Build Web App'
  pool:
    vmImage: 'windows-2019'
  variables:
    BuildConfiguration: release
    system.debug: true
  
  steps:
  
  - task: UseDotNet@2
    displayName: Install .NET 6 sdk
    inputs:
      packageType: sdk
      version: 6.0.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # - task: DotNetCoreCLI@2
  #   displayName: Restore
  #   inputs:
  #     command: restore
  #     projects: '**/WebApp.csproj'
  
  # - powershell: |
  #    $paths = Get-ChildItem -include *.csproj -Recurse
  #    foreach($pathobject in $paths) 
  #    {
  #        $path = $pathobject.fullname
  #        $doc = New-Object System.Xml.XmlDocument
  #        $doc.Load($path)
  #        $child = $doc.CreateElement("ProjectGuid")
  #        $child.InnerText = [guid]::NewGuid().ToString().ToUpper()
  #        $node = $doc.SelectSingleNode("//Project/PropertyGroup")
  #        $node.AppendChild($child)
  #        $doc.Save($path)
  #    }
  #   workingDirectory: WebApp
  #   displayName: 'PS : Add Project GUID'
  #   enabled: false
  
  # - task: SonarCloudPrepare@1
  #   displayName: 'Prepare analysis on SonarCloud'
  #   inputs:
  #     SonarCloud: SonarCloud
  #     organization: chethan-kimi
  #     projectKey: 'WebAppWithDatabaseDemo'

  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       Write-Host "##[group]Debug on & Java info"
  #       $env:SONAR_SCANNER_OPTS = "-Xmx1024m -Dsonar.verbose=true -Dsun.zip.disableMemoryMapping=true"
  #       echo "SONAR_SCANNER_OPTS=$env:SONAR_SCANNER_OPTS"
  #       java -version
  #       Write-Host "##[endgroup]"

  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       - powershell: |
  #           Write-Host "=== java -version ==="
  #           java -version
  #           Write-Host "where java:"
  #           where.exe java
  #           Write-Host "JAVA_HOME:"
  #           echo %JAVA_HOME%
  #           Write-Host "Setting SONAR_SCANNER_OPTS for verbose output"
  #           setx SONAR_SCANNER_OPTS "-Xmx1024m -Dsonar.verbose=true -Dsun.zip.disableMemoryMapping=true" /M
  #           # also set for current session
  #           $env:SONAR_SCANNER_OPTS = "-Xmx1024m -Dsonar.verbose=true -Dsun.zip.disableMemoryMapping=true"
  #           Write-Host "SONAR_SCANNER_OPTS set to $env:SONAR_SCANNER_OPTS"
  #         displayName: 'Print Java info & enable Sonar verbose'
  #         shell: powershell

  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       - powershell: |
  #           Write-Host "=== checking .sonarqube/out ==="
  #           $out = Join-Path $(Build.SourcesDirectory) ".sonarqube\out"
  #           if (Test-Path $out) {
  #             Get-ChildItem -Path $out -Recurse | Select-Object FullName -First 200
  #             if (Test-Path (Join-Path $out "sonar-project.properties")) { Get-Content (Join-Path $out "sonar-project.properties") -TotalCount 200 }
  #             else { Write-Host "sonar-project.properties NOT FOUND in $out" }
  #           } else {
  #             Write-Host ".sonarqube/out NOT FOUND at $out"
  #           }
  #         displayName: 'Check sonar begin metadata'
  #         shell: powershell
      
  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       - powershell: |
  #           Write-Host "Cleaning local Sonar temp/out artifacts"
  #           Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$(Build.SourcesDirectory)\.sonarqube\out\*"
  #           Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$(Agent.TempDirectory)\*sonar*"
  #           Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$(Agent.TempDirectory)\.sonar\*"
  #         displayName: 'Clean Sonar temp files'
  #         shell: powershell

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        java -version
        where.exe java
        echo %JAVA_HOME%
        dir D:\a\1\.sonarqube\out
        type D:\a\1\.sonarqube\out\sonar-project.properties
        dir D:\a\_tasks\SonarCloud*

        
  - task: SonarCloudPrepare@3
    displayName: 'Prepare analysis on SonarCloud'
    inputs:
      SonarQube: 'SonarCloud'
      organization: 'chethan-kimi'
      scannerMode: 'dotnet'
      projectKey: 'WebAppWithDatabaseDemo'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/WebApp.csproj'
      arguments: '--configuration $(BuildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*UnitTest*.csproj'
      arguments: '--configuration $(BuildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True

  - task: SonarCloudAnalyze@3
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'
    displayName: 'Run Code Analysis'

  # - task: SonarCloudAnalyze@1
  #   inputs:
  #     jdkversion: 'JAVA_HOME_21_X64'
  #   displayName: 'Run Code Analysis'
  
  - task: SonarCloudPublish@3
    displayName: 'Publish Quality Gate Result'
    # inputs:
    #   pollingTimeoutSec: '300'
  # - task: SonarCloudPublish@1
  #   displayName: 'Publish Quality Gate Result'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact (WebApp.zip)'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

# - job: Database
#   displayName: 'Build Database'
#   pool:
#     vmImage: 'windows-2019'

#   steps:
#   - task: MSBuild@1
#     displayName: 'Build solution WebApp.Database.sqlproj'
#     inputs:
#       solution: WebApp.Database/WebApp.Database.sqlproj
#       msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'
  
#   - task: PublishBuildArtifacts@1
#     displayName: 'Publish Artifact (Dacpac)'
#     inputs:
#       ArtifactName: dacpac

# - job: Selenium
#   displayName: 'Build UI Tests'
#   pool:
#     vmImage: 'windows-2019'

#   steps:
#   - task: NuGetToolInstaller@0
#     displayName: 'Use NuGet 4.3.0'

#   - task: NuGetCommand@2
#     displayName: 'NuGet restore'
#     inputs:
#       restoreSolution: WebAppWithDatabase.sln

#   - task: MSBuild@1
#     displayName: 'Build project SeleniumUiTests.csproj'
#     inputs:
#       solution: SeleniumUiTests/SeleniumUiTests.csproj
#       msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

#   - task: PublishBuildArtifacts@1
#     displayName: 'Publish Artifact: UI-Test'
#     inputs:
#       ArtifactName: 'UI-Test'

# - job: Infrastructure
#   displayName: 'Copy Infrastructure files (ARM)'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - task: PublishBuildArtifacts@1
#     displayName: 'Publish Artifact: ARM templates'
#     inputs:
#       PathtoPublish: AzureResourceGroupDeployment
#       ArtifactName: arm


